import{a as w,S as v,i as n}from"./assets/vendor-DEenWwFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();function m({webformatURL:r,largeImageURL:t,tags:s,likes:i,views:e,comments:o,downloads:a}){return`<li class="gallery-item">
            <a href="${t}" class="gallery__item">
      <img src="${r}" alt="${s}" loading="lazy" class="gallery__image" />
      <div class="gallery__info">
        <p><b>Likes:</b> ${i}</p>
        <p><b>Views:</b> ${e}</p>
        <p><b>Comments:</b> ${o}</p>
        <p><b>Downloads:</b> ${a}</p>
      </div>
    </a>
        </li>`}const y=async(r,t)=>{const s={params:{key:"48307902-b3b0ba5bf2bf175d4af253477",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}};try{return(await w.get("https://pixabay.com/api/",s)).data}catch(i){throw new Error(i.response.status)}},g=document.querySelector(".search-form"),p=document.querySelector(".gallery"),u=document.querySelector(".loader"),h=document.querySelector(".loader-bottom"),c=document.querySelector(".load-more-btn"),f=new v(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});let l=1,d="";async function S(r){if(r.preventDefault(),d=g.elements.user_query.value.trim(),d===""){n.error({message:" Please fill this field. The field should not be empty!",position:"topRight"});return}l=1,c.classList.add("is-hidden"),p.innerHTML="",u.style.display="block";try{const t=await y(d,l);if(t.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}const s=t.hits.map(m).join("");p.innerHTML=s,f.refresh(),t.hits.length===15&&t.totalHits>15&&c.classList.remove("is-hidden"),b()}catch(t){n.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.log(t)}finally{u.style.display="none"}}function b(){const r=p.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}g.addEventListener("submit",S);c.addEventListener("click",L);async function L(){try{l++,h.style.display="block";const r=await y(d,l),t=r.hits.map(m).join("");p.insertAdjacentHTML("beforeend",t),f.refresh(),b(),(r.hits.length<15||l>=Math.ceil(r.totalHits/15))&&(c.classList.add("is-hidden"),c.removeEventListener("click",L),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){n.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(r)}finally{h.style.display="none"}}
//# sourceMappingURL=index.js.map
